version: "3.8"

services:
  poks-client:
    build:
      context: .
      dockerfile: ./poks-client/Dockerfile
    ports:
      - 8080:8080

  poks-server:
    build: ./poks-server
    ports:
      - 44443:44443
