version: "3.8"

services:
  estimatron-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 8080:8080

  estimatron-server:
    build: ./server
    ports:
      - 44443:44443
