name: CI

on:
  push:
    branches:
      - master
      - ci
    pull_request:
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
        working-directory: ./poks-server
      - run: npm test
        working-directory: ./poks-server
        env:
          CI: true

      - run: npm install
        working-directory: ./poks-client
      - run: npm test
        working-directory: ./poks-client
        env:
          CI: true
